spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: false
tenants:
  datasources:
    first:
      jdbcUrl: jdbc:mysql://localhost:3306/app_db_001?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      username: root
      password: root
    second:
      jdbcUrl: jdbc:mysql://localhost:3306/app_db_002?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      username: root
      password: root
    third:
      jdbcUrl: jdbc:mysql://localhost:3306/app_db_003?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      username: root
      password: root
